name: Continuous Integration

on:
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Format code
      uses: iamnotaturtle/auto-gofmt@v2.1.0