name: CI
on:
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: './cmd'
          gofmt-flags: '-l -d'